spring:
  application:
    name:  payment-service

server:
  port: 8002

eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
